
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class PrintAdmin extends javax.swing.JFrame {
        Connection conn;
        ResultSet rs;
        PreparedStatement pst;
        double dhakatick =0, rajtick=0, chittick=0, bartick=0;
    int sD =0, sR =0, sC= 0, sB=0;
    /**
     * Creates new form Customers
     */
    public PrintAdmin() {
        initComponents();
        conn = javaConnect.ConnectDB();
      setDefaultCloseOperation(DISPOSE_ON_CLOSE);
   
    }
 
    
     
      
        
    
    
        
    
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\DOWNLOAD\\PROJECT\\priBAN.jpg")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(62, 54, 75));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Get Sales Report including Total Revenue and Total Tickets Sold");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, 30));

        jButton1.setBackground(new java.awt.Color(51, 0, 102));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 255));
        jButton1.setText("PRINT INFO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 110, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String sql = "select * from ticketDetails where source = 'Dhaka'";
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                double dhakaprice  = Double.parseDouble(rs.getString(9));
                int ch = Integer.parseInt(rs.getString("childTicket"));
                int ad = Integer.parseInt(rs.getString("adultTicket"));
                sD = sD + ch + ad;
                dhakatick = dhakatick+dhakaprice;
                
            }
         //   System.out.println("The total earnings of bus leaving from Dhaka is: " + totalEarningD + " and the total number of tickets are: " + sD);
            
        }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }
        
         
        String sql1 = "select * from ticketDetails where source = 'Rajshahi'";
        try{
            pst = conn.prepareStatement(sql1);
            rs = pst.executeQuery();
            while(rs.next()){
                double rajprice = Double.parseDouble(rs.getString(9));
                int ch = Integer.parseInt(rs.getString("childTicket"));
                int ad = Integer.parseInt(rs.getString("adultTicket"));
                sR = sR + ch + ad;
                rajtick = rajtick+rajprice;
            }
         //   System.out.println("The total earnings of bus leaving from Rajshahi is: " + totalEarningR + " and the total number of tickets are: " + sR);
        }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }
        
        String sql2 = "select * from ticketDetails where source = 'Chittagong'";
        try{
            pst = conn.prepareStatement(sql2);
            rs = pst.executeQuery();
            while(rs.next()){
                double chitprice = Double.parseDouble(rs.getString(9));
                int ch = Integer.parseInt(rs.getString("childTicket"));
                int ad = Integer.parseInt(rs.getString("adultTicket"));
                sC = sC + ch + ad;
                chittick = chittick+chitprice;
            }
        //    System.out.println("The total earnings of bus leaving from Chittagong is: " + totalEarningC + " and the total number of tickets are: " + sC);
        }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }
        
        String sq3 = "select * from ticketDetails where source = 'Barishal'";
        try{
            pst = conn.prepareStatement(sq3);
            rs = pst.executeQuery();
            while(rs.next()){
                double barprice = Double.parseDouble(rs.getString(9));
                
                int ch = Integer.parseInt(rs.getString("childTicket"));
                int ad = Integer.parseInt(rs.getString("adultTicket"));
                sB = sB + ch + ad;
                bartick = bartick+barprice;
            }
           // System.out.println("The total earnings of bus leaving from Barishal is: " + totalEarningB + " and the total number of tickets are: "+ sB);
        }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
       }
    
        double totalSale = dhakatick + rajtick + chittick + bartick;
        int totalTick = sD+sR+sC+sB;
        
        
            try {
                pdfWrapper2.pdfHandler(dhakatick, sD, rajtick, sR, chittick, sC, bartick, sB, totalSale, totalTick);
            } catch (Exception ex) {
                Logger.getLogger(PrintAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new PrintAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
